#On which worlds should a Players inventory be cleared when he leaves it?
   AffectedWorlds:

   - "world"

#//////////////////////////////////////////////////////
#//                                                  //
#//     ClearInvOnWorldChange by DarkWav.            //
#//     Distributed under the GGPL License.          //
#//                                                  //
#//////////////////////////////////////////////////////
...
